### PR TITLE
Full Userguide restructure

### PR DESCRIPTION
**Pull request by Robadob**
WIP based on internal document: https://docs.google.com/document/d/1Nh0MR5YZXwuP-3SXZAN1kYhGgaIbnz6bg33I6-biSO4/edit?usp=sharing

### CODE REVIEW

**Comment by Robadob** [comment]
K there's now a build of the current tutorial state: https://github.com/FLAMEGPU/FLAMEGPU2-docs/suites/5206091718/artifacts/159093567

**Comment by Robadob** [comment]
Would be useful to get some reviews of this first draft of the new tutorial.

https://github.com/FLAMEGPU/FLAMEGPU2-docs/suites/5207502606/artifacts/159177534

**Comment by mondus** [comment]
Noticed that docs does not include
- [ ] description of return type in agent functions description
- [ ] agent device random

**Comment by Robadob** [comment]
https://github.com/FLAMEGPU/FLAMEGPU2-docs/suites/5989171640/artifacts/206463233
Convenient latest artefact link if you cba to build before reviewing.

**Comment by Robadob** [comment]
Latest artefacts: https://github.com/FLAMEGPU/FLAMEGPU2-docs/suites/6090247155/artifacts/211073499

**Pull request merged**
