### PR TITLE
Remove numbers from file names.

### PR DESCRIPTION
**Pull request by Robadob**
The 3 links in this discussion will need updating (again): https://github.com/FLAMEGPU/FLAMEGPU2/discussions/715#discussioncomment-1508823

I skimmed the other discussions earlier, and couldn't spot any docs links, and I assume readme has no links.

### CODE REVIEW

**Review by ptheywood — APPROVED** [review]
Looks good, I've done a quick `find` for all the rst files and none begin with numbers. I've not checked all links, but there are no (related) warnings when building without the API docs atleast. 

There are however a number of RST warnings which could be addressed, that will get lost to the noise of breathe / exhale repeated warnings. 

```
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/agent-functions/agent-birth-death.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/agent-functions/agent-communication.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/agent-functions/agent-communication.rst:8: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/agent-functions/defining-agent-functions.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/agent-functions/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/agent-functions/interacting-with-environment.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/agent-functions/random-numbers.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/creating-a-model/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-agents/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-agents/index.rst:68: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-execution-order/dependency-graph.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-execution-order/exit-conditions.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-execution-order/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-execution-order/layers.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-execution-order/submodels.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/defining-messages-communication/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/environment/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/environment/index.rst:76: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/agent-operations.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/agent-operations.rst:29: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/agent-operations.rst:161: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/agent-operations.rst:204: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/defining-host-functions.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/interacting-with-environment.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/interacting-with-environment.rst:64: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/random-numbers.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/host-functions/random-numbers.rst:44: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/running-a-simulation/collecting-data.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/running-a-simulation/collecting-data.rst:13: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/running-a-simulation/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/running-a-simulation/initial-state.rst:13: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/running-a-simulation/initial-state.rst:157: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/seatbelts/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/guide/visualisation/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/index.rst:9: WARNING: toctree contains reference to nonexisting document 'api/library_root'
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/quickstart/index.rst:2: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/quickstart/index.rst:11: WARNING: Explicit markup ends without a blank line; unexpected unindent.
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/quickstart/index.rst:74: WARNING: Explicit markup ends without a blank line; unexpected unindent.
```

With all of breathe / exhale's warnings these get lost in builds with them / we can't enable a warnings as erros equivalent on CI easily. 

I could look at adding GHA annotations as in the main repo, but again this will be a wall of noise from API included warnings (unless they are easily distinguished or suppressed). I'll open a new issue.

**Comment by Robadob** [comment]
> I've not checked all links

I updated all the `index.rst` files, all other links I'm aware of use cross-ref labels not file names.

**Comment by Robadob** [comment]
image
Looks like, it wants a blank line after those labels. So probably every single label needs the blank link adding.

**Comment by Robadob** [comment]
@ptheywood I presume this will fix all of those warnings, besides the `api/library_root` missing one.

**Comment by ptheywood** [comment]
Yep, plus a 

> @ptheywood I presume this will fix all of those warnings, besides the `api/library_root` missing one.

Yep those are resolved now. 

There's also one emitted when procesing the tutorial I hadn't pasted earlier as it wasn't in the same large block. 

```
/home/ptheywood/code/flamegpu/FLAMEGPU2-docs/src/tutorial/index.rst:499: WARNING: Could not lex literal_block as "py". Highlighting skipped.
```

Which maps to 

```
  .. code-tab:: py Python

    ...
        return flamegpu::ALIVE;
    }
    """
```

which is c++ anyway, so that could do with tweaking (Can be part of this or independent)

**Comment by Robadob** [comment]
> Probably best to comment out the lines with the elipses at the very least

It is, I'm aware of that warning and have chosen to ignore it tbh. There wasn't a nice way to address it and the code is 99% a huge string literal so highlighting isn't too useful.

**Comment by ptheywood** [comment]
> > Probably best to comment out the lines with the elipses at the very least
> 
> I think it's actually due to only the closing of the string literal, I'm aware of that warning and have chosen to ignore it tbh. There wasn't a nice way to address it and the code is 99% a huge string literal so highlighting isn't too useful.

Yeah it'll be the string that breaks the parsing, I'd prefer the elipses as comments but that's probably just me. If you don't want it parsing as python, the way to address the warning is to not ask it to be lexed as python at all (i.e. change `py` to  to the sphinx/pygments plain text lexer, which I think is `text`).

**Comment by Robadob** [comment]
I would like it parsed as Python, that simply not possible (without removing the hints to where it's located within a file. Removing the string literal thingy would be preferable I guess.

**Comment by ptheywood** [comment]
The issue is present in other code blocks, but rather than warnings being generated the lexing is just wrong:

image

It's probably worth promoting to it's own issue / separte discussion and merging this PR as it's an independent problem, and getting the URIs to their correct destination shouldn't be blocked by it.

**Comment by Robadob** [comment]
> It's probably worth promoting to it's own issue / separte discussion and merging this PR as it's an independent problem, and getting the URIs to their correct destination shouldn't be blocked by it.

Sure, I think it's limited to the tutorial regardless. Don't believer other code is self referential.

**Comment by ptheywood** [comment]
Opened https://github.com/FLAMEGPU/FLAMEGPU2-docs/issues/83

**Pull request merged**
